{{- define "imagePullSecret" }}
{{- with .Values.imageCredentials }}
{{- printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace "registry-credentials" ) -}}

apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
{{ if $secret -}}
data:
  .dockerconfigjson: {{ get $secret.data ".dockerconfigjson" }}
{{ else -}}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
