name: Build Docker image and push to Azure

on:
  push:
    branches:
      - main
      - feature/start

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Azure Container Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.AZURE_CLIENTID }}
          password: ${{ secrets.AZURE_SECRET }}
          registry: ${{ secrets.ACR_URL }}
      - name: Prepare tags
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.ACR_URL }}/nhsei-website
          VERSION=edge
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}
          TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA}"
          echo ::set-output name=tags::${TAGS}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
