name: Build Docker image and push to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy-version: ${{ steps.prep.outputs.deploy-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Azure Container Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.TESTING_AZURE_ACR_CLIENTID }}
          password: ${{ secrets.TESTING_AZURE_ACR_SECRET }}
          registry: ${{ secrets.TESTING_ACR_URL }}
      - name: Prepare tags
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.TESTING_ACR_URL }}/nhsei-website
          VERSION=edge
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [ "${{ github.event_name }}" = "push" ]; then
            VERSION=sha-${GITHUB_SHA}
            TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION}"
          fi
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=deploy-version::${VERSION}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTING_AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ secrets.TESTING_AZURE_CLUSTER_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.TESTING_AZURE_CLUSTER_NAME }}
      - uses: azure/setup-helm@v1
      - name: Install with Helm
        run: |
          helm upgrade --reuse-values nhsei-testing-web deployment/helm/nhsei-website \
            --set-string image.tag=${{ needs.build.outputs.deploy-version }}
