name: Build Docker image and push to Azure

on:
  push:
    branches:
      - main
      - feature/start

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy-version: ${{ steps.prep.outputs.deploy-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Azure Container Registry login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.AZURE_CLIENTID }}
          password: ${{ secrets.AZURE_SECRET }}
          registry: ${{ secrets.ACR_URL }}
      - name: Prepare tags
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.ACR_URL }}/nhsei-website
          VERSION=edge
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [ "${{ github.event_name }}" = "push" ]; then
            VERSION=sha-${GITHUB_SHA}
            TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION}"
          fi
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=deploy-version::${VERSION}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_CLUSTER_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
      - uses: azure/setup-helm@v1
      - name: Install with Helm
        run: |
          helm upgrade --install nhsei-website deployment/helm/nhsei-website \
            --set-string image.tag=${{ needs.build.outputs.deploy-version }} \
            --set-string imageCredentials.registry=${{ secrets.ACR_URL }} \
            --set-string imageCredentials.username=${{ secrets.AZURE_CLIENTID }} \
            --set-string imageCredentials.password=${{ secrets.AZURE_SECRET }} \
            --set ingress.tls.hosts="{${{ join(secrets.ALLOWED_HOSTS) }}}" \
            --set ingress.hostnames="{${{ join(secrets.ALLOWED_HOSTS) }}}" \
            --set-string environment.allowed_hosts="www.england.nhs.uk\,${{ join(secrets.ALLOWED_HOSTS, '\,') }}" \
            --set-string environment.database_url="${{ secrets.DATABASE_URL }}" \
            --set-string environment.azure_container="website-media" \
            --set-string environment.azure_connection_string="${{ secrets.AZURE_CONNECTION_STRING }}"
